# Generated by Django 4.1.1 on 2024-04-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permissions',
            table='permissions',
        ),
    ]
