# Generated by Django 4.1.1 on 2022-10-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default='2022-10-26 13:27:44'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
