# Generated by Django 4.1.1 on 2022-10-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_topic_content_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='has_photos',
            field=models.BooleanField(default=False),
        ),
    ]
