# Generated by Django 4.1.1 on 2022-09-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_user_profile',
        ),
    ]
